### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by misraved** [sensepost/steampipe-plugin-projectdiscovery#1]
Hi @leonjza  - Great to see all the work on the ProjectDiscovery plugin for Steampipe 🎉 !!

We'd also love to collaborate with you to get this plugin reviewed & listed on the Steampipe Hub so people can find it, use it and hopefully contribute as well - I'm sure it will be useful for others! 

The initial plugin structure looks great. While using the plugin we came up with a few suggestions on our [best practices](https://steampipe.io/docs/develop/plugin-release-checklist):

- `config/projectdiscovery.spc`
  - The plugin argument in the `spc` file should be  `sensepost/projectdiscovery`. In general, we use the org name for plugin reference - https://github.com/marekjalovec/steampipe-plugin-make/blob/main/config/make.spc#L2
  - Thanks for adding links to retrieve the config arguments. They definitely make it easy for the plugin users.
  - The formatting of the file is slightly off, could you please update it as follows:
 ```
  connection "projectdiscovery" {
    plugin = "sensepost/projectdiscovery"
  
    # Naabu
  
    # Top ports to scan for naabu.
    # Can be one of: full, 100, 1000
    # naabu_top_ports = "100"
  
    # Chaos
  
    # Project chaos API key. Sign up for an API key at: https://chaos.projectdiscovery.io/
    # chaos_api_key = "enpg9i8k4uxl0jtzoutym44cpm6rbxskr6fqoz11mxxpkiqtn4l7oju66rlqqz8j"
  
    # Cloudlist
  
    # Digital Ocean API key. Get an API key post authentication for a team by browsing to:
    # API (bottom left) -> Personal access tokens
    # A read-only key would suffice
    # cloudlist_do_token = "dop_v1_y0jzo0bp8wl7f3t0px74jea5hnxiicz1sl58z5mso6ep6a544v3mq1jp2qj4ed6a"
}
```

- `docs/tables/*`
  - Overall the docs look great, and the queries are neat, however, the formatting of the example queries needs to be updated per https://www.freeformatter.com/sql-formatter.html#before-output (2 spaces per indent level)
  - Certain table docs just have a single query like https://github.com/sensepost/steampipe-plugin-projectdiscovery/blob/master/docs/tables/projectdiscovery_dnsx.md, https://github.com/sensepost/steampipe-plugin-projectdiscovery/blob/master/docs/tables/projectdiscovery_naabu.md, would it be possible to add a couple of more example queries to the table docs?

- `docs/index.md` and `README` 
  - The doc files look great. You could make minor formatting updates per the [namecheap](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/README.md) plugin docs
  - The references to the social-graphics and icons are missing. You could take a look at https://github.com/marekjalovec/steampipe-plugin-make/blob/main/docs/index.md for more reference.
  - The doc file has a reference to an `api_key` for authenticated access in https://github.com/sensepost/steampipe-plugin-projectdiscovery/blob/master/docs/index.md#configuration , Is this correct?
  - Is there a specific reason for choosing `osint` as the plugin category?
  - The [Get Involved](https://github.com/sensepost/steampipe-plugin-projectdiscovery/blob/master/docs/index.md#get-involved) section incorrectly references `https://github.com/kaggrwal/steampipe-plugin-bitfinex` instead of `https://github.com/sensepost/steampipe-plugin-projectdiscovery`

- `Makefile`
    - Please update the install command as follows - 
        `go build -o ~/.steampipe/plugins/hub.steampipe.io/plugins/sensepost/projectdiscovery@latest/steampipe-plugin-projectdiscovery.plugin *.go`
    - Is there a specific reason why we need to add the `local` installation command?
        
- projectdiscovery/*
  - The table structure, column names, and the logging section look great. very neat indeed 👍!!
  
- A couple of follow-up questions:
    - How are we handling the resource not found errors?
    - Do the APIs support pagination?
    - While working with the APIs did you encounter rate limit errors? 
    - Please refer to https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information
    
Overall the plugin looks great @leonjza. Thanks for all the effort. Please let us know if you have questions. Happy to help 👍.
Once the suggestion/feedback comments are addressed, we could release it to the hub 👍.

**Comment by leonjza** [comment]
Thank you, I did work through the plugin release checklist and other examples for the overall structure. I appreciate the feedback and will update this ticket once I've actioned it all.

**Comment by leonjza** [comment]
Thanks again for the comprehensive feedback. I've actioned them in https://github.com/sensepost/steampipe-plugin-projectdiscovery/commit/d025883a835e8955abecadb1f843579ba26fccd0 as follows:

> * The plugin argument in the `spc` file should be  `sensepost/projectdiscovery`

Added `sensepost` here.

> * The formatting of the file is slightly off, could you please update it as follows:

Updated, mostly just changing the comment character from `//` to `#`.

> * Overall the docs look great, and the queries are neat, however, the formatting of the example queries needs to be updated per https://www.freeformatter.com/sql-formatter.html#before-output (2 spaces per indent level)

I ran all of the queries through the formatter as suggested and updated the examples with the results.

> * Certain table docs just have a single query

Some of these tables is really, really simple, but I added one more for `_naabu`.

> * The doc files look great. You could make minor formatting updates per the [namecheap](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/README.md) plugin docs

Thanks. There are links there that would point to hub.steampipe.io that do not exist. Once/if the plugin becomes listed I'll add/update those.

> * The references to the social-graphics and icons are missing.

I don't have any graphics to link.

> * The doc file has a reference to an `api_key` for authenticated

Update to the correct key names.

> * Is there a specific reason for choosing `osint` as the plugin category?

Yes, the projectdiscovery toolsets are used in footprinting, reconnaissance, open source intelligence.

> * The [Get Involved](https://github.com/sensepost/steampipe-plugin-projectdiscovery/blob/master/docs/index.md#get-involved) section incorrectly references

Updated.

> * Please update the install command as follows

Done.

> * s there a specific reason why we need to add the `local` installation command?

Left over debugging code. Removed it now.

> * How are we handling the resource not found errors?

The tables just have empty results then.

> * Do the APIs support pagination?

Not all of the tools make use of traditional API's (eg. naabu). However, in the case of cloudlist, pagination is handled by the [underlying library](https://github.com/projectdiscovery/cloudlist/blob/v1.0.3/pkg/providers/digitalocean/instances.go#L17).

> * While working with the APIs did you encounter rate limit errors?

No.

**Comment by misraved** [comment]
Thanks @leonjza for the quick update 👍.

We will be taking care of the social graphics and icon, apologies for making the process sound so complicated, but you could update the `docs/index.md` file to use the following references for the social graphics plugin -
```
---
organization: Sensepost
category: ["osint"]
icon_url: "/images/plugins/sensepost/projectdiscovery.svg"
brand_color: "#2684FF"
display_name: "Project Discovery"
short_name: "projectdiscovery"
description: "Steampipe plugin for interacting with projectdiscovery.io toolsets."
og_description: "Query ProjectDiscovery with SQL! Open source CLI. No DB required."
og_image: "/images/plugins/sensepost/projectdiscovery-social-graphic.png"
---
```

Similarly, the `README` file could be updated to use the following social graphic reference:
`![image](https://hub.steampipe.io/images/plugins/sensepost/projectdiscovery-social-graphic.png)`

**Comment by leonjza** [comment]
> , but you could update the `docs/index.md` file to use the following references for the social graphics plugin

I added this.



> Similarly, the `README` file could be updated to use the following social graphic reference:

This goes 404. Will wait for something to be there before adding it to the README.

**Comment by leonjza** [comment]
> > , but you could update the `docs/index.md` file to use the following references for the social graphics plugin
> 
> I added this.
> 
> > Similarly, the `README` file could be updated to use the following social graphic reference:
> 
> This goes 404. Will wait for something to be there before adding it to the README.

Actually, when looking at other repos, I'd prefer we don't add this banner to the readme. Is that going to be a blocker for you to publishing?

**Comment by misraved** [comment]
Not a blocker @leonjza 👍.

Thanks for updating the `docs/index.md` file 👍.

**Comment by leonjza** [comment]
Just to close the loop here, anything else I need to do for publishing?

**Comment by misraved** [comment]
@leonjza I am taking a final look at the plugin structure. Overall it looks good for a release, but we are just waiting on the social graphics and icon 👍.

We can then push the plugin to the hub 👍.

**Comment by misraved** [comment]
@leonjza Is there a specific reason why we have not commented out `naabu_top_ports` in `config/projectdiscovery.spc` and `docs/index.md` files?

**Comment by leonjza** [comment]
In my mind it's because that is the suggested default value folks should use, but obviously can change.

**Comment by misraved** [comment]
> In my mind it's because that is the suggested default value folks should use, but obviously can change.

I don't think it's a deal breaker, but I think we could handle it in the code in a better way, like if the user does not pass in a value, we could fall back on port `100`.

Couple of other enhancements that we could implement:
- I think we should update the table docs to explicitly mention which config arguments are required to query each table. This could also be mentioned in the docs/index.md file.
- Is there a specific reason as to why we have not followed the error logging used across other plugins? For instance, https://github.com/sensepost/steampipe-plugin-projectdiscovery/blob/master/projectdiscovery/table_projectdiscovery_dnsx.go#L50 could be replaced by `logger.Error("projectdiscovery_dnsx.listDnsxScan", "api_error", err)`. Similarly, https://github.com/sensepost/steampipe-plugin-projectdiscovery/blob/master/projectdiscovery/table_projectdiscovery_dnsx.go#L44 should also include `logger.Error("projectdiscovery_dnsx.listDnsxScan", "connection_error", err)`.

**Comment by leonjza** [comment]
v0.1.1 should be good to go.
